### PR TITLE
Connections UX improvements

### PR DESCRIPTION
**Pull request by qgerome**
The goal was to improve the user experience when creating and editing the connections. Some fields were not easy to grasp and it was hard for our users to fill in the creation form smoothly.

## Changes

- Add help & placeholder on inputs where it makes sense
- Display the same form as in the creation when user want to update a connection
- Add validation in the form

## How/what to test

Connections in general (at least a custom and another one)

## Screenshots / screencast

If relevant, please add some screenshots or a short video.

### CODE REVIEW

**Comment by qgerome** [comment]
Uploading Screen Recording 2023-07-14 at 17.16.38.mov…

**Comment by qgerome** [comment]
https://github.com/BLSQ/openhexa-frontend/assets/1607549/b5627664-f610-45ea-b7cb-83eddca3bfd9

**Comment by qgerome** [comment]
https://github.com/BLSQ/openhexa-frontend/assets/1607549/26d8506c-c080-4c7f-b29d-940f9d399bdf

**Comment by qgerome** [comment]
I've set the miminum height of the screen to 900px, do you agree with that @pvanliefland

**Review by pvanliefland — APPROVED** [review]
👍

**Review by cheikhgwane — APPROVED** [review]
LGTM!

**Pull request merged**
