### PR TITLE
feat(Workspaces): update database and connections usage sections links

### PR DESCRIPTION
**Pull request by cheikhgwane**
Update connections and database usage section.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Add wiki links  (general doc, usage in notebooks, usage in pipelines) for connections
- Add wiki links  (general doc, usage in notebooks, usage in pipelines) for database

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast
Database
image

Connection
image

### CODE REVIEW

**Comment by cheikhgwane** [comment]
@pvanliefland You can check for the text also?

**Comment by pvanliefland** [comment]
@cheikhgwane I would rather present this as a list with three links, such as :

- Connections general documentation
- Using connections in notebooks
- Using connections in pipelines

@qgerome wdyt?

**Comment by qgerome** [comment]
> @cheikhgwane I would rather present this as a list with three links, such as :
> 
> * Connections general documentation
> * Using connections in notebooks
> * Using connections in pipelines
> 
> @qgerome wdyt?

Agreed

**Comment by cheikhgwane** [comment]
@qgerome I've added some texts

**Pull request merged**
