### PR TITLE
chore(Nextjs): Add a trailing slash to nextjs urls

### PR DESCRIPTION
**Pull request by qgerome**
To be able to make relative links in the wiki, we'd need to have trailing slash in the urls.
NextJS provides this feature but we need to test if it works well in legacy mode and with the navigation in the workspaces.

### CODE REVIEW

**Review by cheikhgwane — APPROVED** [review]

**Comment by pvanliefland** [comment]
It seems that it's not working as expected for now, let's put it on hold

**Comment by qgerome** [comment]
> It seems that it's not working as expected for now, let's put it on hold

Oh :( What was not working ? I tested it on local and it worked. Do you have an example of URL that did not work ?

**Comment by pvanliefland** [comment]
@qgerome sorry, I should have been more specific when I wrote that comment. Now I'm not sure anymore, but I there was an issue in "OpenHexa legacy". @cheikhgwane do you remember?

**Comment by cheikhgwane** [comment]
> @qgerome sorry, I should have been more specific when I wrote that comment. Now I'm not sure anymore, but I there was an issue in "OpenHexa legacy". @cheikhgwane do you remember?

Yes, it works now (legacy and workspace)

**Comment by pvanliefland** [comment]
Already in `main`

**Pull request closed without merging**
