### PR TITLE
fix(Pipelines): validate form data before submit

### PR DESCRIPTION
**Pull request by cheikhgwane**
If there is a select in the PipelineRunDialog form, I can edit the select, delete the initial value and click on Run.The field will not be validated.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Add validate function on PipelineRunDialog useForm

## How/what to test

A few words about what needs to be tested, along with specific testing instructions if needed.

## Screenshots / screencast

image

### CODE REVIEW

**Review by qgerome — COMMENTED** [review]
It looks nice, I'll test tomorrow

**Review by qgerome — APPROVED** [review]

**Comment by qgerome** [comment]
@cheikhgwane Have you checked that the error is displayed in the form ?

**Comment by cheikhgwane** [comment]
@qgerome error from the pipeline validation on the front or when we click on run and there's an error?

**Comment by qgerome** [comment]
In the frontend. Since you return errors from the validate function, it has to be displayed in the dialog.

**Comment by cheikhgwane** [comment]
@qgerome Yes, I had added (by using form.touched) but it displayed the error even before the field was touched.

**Comment by cheikhgwane** [comment]
@qgerome 

image

**Pull request merged**
